name: choque
favicon: null
layout_spectrum: 0.2751579799223691
typography_spectrum: 0.09867147053591907
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0708'
    - '#2c253a'
    - '#1d1218'
    - '#472729'
    - '#6f3c25'
  brandStrength: 0.9755421332083642
  lightness: 0.01623911061324179
  saturation: 0.9917831800412387
  rhythmicContrast: 0.7169584291987121
purpose: []
