name: choque
favicon: null
layout_spectrum: 0.2751579799223691
typography_spectrum: 0.75313
title: Choque Visuals
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c4c4c4'
    - '#000000'
    - '#959595'
    - '#5c5c5c'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
