name: choque
favicon: null
layout_spectrum: 0.2751579799223691
typography_spectrum: 0.82854
title: Choque Visuals
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0708'
    - '#2c253a'
    - '#1d1218'
    - '#472729'
    - '#6f3c25'
  brandStrength: 1
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
