name: choque
favicon: null
layout_spectrum: 0.2751579799223691
typography_spectrum: 0.80501
title: Choque Visuals
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4d4d4d'
    - '#c6c634'
    - '#dfe1e0'
    - '#989898'
  brandStrength: 0.75
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
